name: lint

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: clang-tidy check
      uses: muxee/clang-tidy-action@0.0.1-rc1
    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.3.1
      with:
        exclude: 'examples/tests,examples/docs,extern/'
